<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseIntegrationApi.Domain\EnterpriseIntegrationApi.Domain.csproj" />
    <ProjectReference Include="..\EnterpriseIntegrationApi.Application\EnterpriseIntegrationApi.Application.csproj" />
    <ProjectReference Include="..\EnterpriseIntegrationApi.Shared\EnterpriseIntegrationApi.Shared.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
