<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.23" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EnterpriseIntegrationApi.Application\EnterpriseIntegrationApi.Application.csproj" />
    <ProjectReference Include="..\EnterpriseIntegrationApi.Infrastructure\EnterpriseIntegrationApi.Infrastructure.csproj" />
    <ProjectReference Include="..\EnterpriseIntegrationApi.Platform\EnterpriseIntegrationApi.Platform.csproj" />
  </ItemGroup>

</Project>
